name: flue
description: A new Flutter project.

version: 1.3.8

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_mobile_ads: ^4.0.0
  shared_preferences: ^2.2.2
  in_app_purchase: ^3.2.0
  floating: ^2.0.2
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.0
  #translator:
  html_unescape: ^2.0.0
  video_player: ^2.9.1
  double_tap_player_view: ^2.0.3
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  carousel_slider: ^4.2.1
  wakelock: ^0.6.1
  url_launcher: ^6.0.12
  connectivity_plus: ^3.0.6
  font_awesome_flutter: ^10.6.0
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.3.0
  image_network: ^2.5.4
  scrollable_positioned_list: ^0.3.8
  dots_indicator: ^2.1.1
  fluttertoast: ^8.2.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  graphql_flutter: ^5.1.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  uuid: ^3.0.4
  crypto: ^3.0.3
  intl: ^0.19.0
  webview_flutter: ^4.4.3
  html: ^0.15.0
  get: ^4.6.1
  flutter_html: ^3.0.0-beta.2
  dio: ^5.4.0
  flutter_downloader: ^1.7.0
  path_provider:
  permission_handler: ^11.1.0
  flex_color_picker: ^3.0.0
  hexcolor: ^3.0.1
  flutter_colorpicker: ^1.0.3
  provider: ^6.1.1
  wave: ^0.2.2
  flutter_svg: ^2.0.9
  photo_view:
  firebase_messaging: ^14.7.10
  open_file: ^3.3.2
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.13
  audio_service: ^0.18.15
  youtube_explode_dart: ^2.2.1
  audio_session:
  flutter_overlay_window: ^0.4.3
  timeago: ^3.0.2
  translator: ^1.0.0
  collection: ^1.18.0
  flutter_chrome_cast: ^0.0.10
  #fijkplayer_update: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/logo.png
    - img/background.jpg
    - img/test.jpg
    - img/logo-splash.svg
    - shorebird.yaml
  fonts:
    - family: Satoshi
      fonts:
        - asset: fonts/Satoshi-Regular.ttf
        - asset: fonts/Satoshi-Black.ttf
        - asset: fonts/Satoshi-Bold.ttf
        - asset: fonts/Satoshi-Light.ttf
        - asset: fonts/Satoshi-Italic.ttf
          style: italic
    # Add more variations as needed
  plugin:
    platforms:
      android:
        package: com.felnanuke.google_cast
        pluginClass: GoogleCastPlugin
